### ISSUE TITLE
문자 오류 제보

### ISSUE THREAD

**Issue by hyde0208** [wooddoll/vagrant_story_korean#1]
![Vagrant Story (Korea)-0001](https://github.com/user-attachments/assets/bf022d24-c51b-4237-9939-a08fdcba25de)
도입부분에 틀린 부분이 있네요~
기사들을 두 조으로 나누어 라고 나옵니다.
화이팅 입니다.

**Comment by wooddoll** [comment]
v0.81에 반영되었습니다. 
감사합니다.
