### ISSUE TITLE
베이그란트 스토리 한글버그 v0.91

### ISSUE THREAD

**Issue by cclownc** [wooddoll/vagrant_story_korean#3]
![2024110718042100-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/79990de4-aed6-4c74-9f7e-16ad3f45fb4a)
전멸한 녀석'늘'

![2024110720345700-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/4e3d8f88-c98f-499c-8e85-fcc6d2234a7e)
소지 무기보다 더 얻으면 나오는 창

![2024110720351800-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/b67ec21a-7519-42dc-9d4c-7efab5c80f5e)
분해 후 선택지

![2024110714363700-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/139906b6-87bd-49da-a75d-a4cb34816c92)
숏컷 아이템 선택 후 '봤북'

![2024110716015600-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/cfa80717-fb0f-49ee-8fe6-e932a27d9786)
특정무기 파밍 후 이름

**Comment by wooddoll** [comment]
알려주셔서 감사합니다.
지역명이 어딘가요? '버밀리온 거리' 조금 지나서 인가요?

**Comment by cclownc** [comment]
와인저장고를 나오고 나서 이벤트였던 것으로 기억 합니다.

그리고 진행불가 버그가 있습니다.
보스로 오우거를 잡고 나서 밖으로 나가는 이벤트를 보고 난 후
다른 키는 눌리는데  메뉴소환버튼(플스로는 네모키)이 눌리지 않습니다.

일본어 버전에서 확인해보니
한글패치 버전에는 이벤트 누락 장면이 있습니다.
오우거를 잡고나서 밖으로 나가는 이벤트가 일본어버전에서는 여자동료로 들어가는 연출이 있는데.
한글패치 버전은 그냥 제자리에 쓰러지고 이벤트가 진행되었습니다.


[Vagrant Story (kv0.91)mcd.zip](https://github.com/user-attachments/files/17677867/Vagrant.Story.kv0.91.mcd.zip)
혹시 몰라 세이브 파일 첨부했습니다. 1번째 슬롯입니다.

세이브포인트에서 거리가 있어서 오우거 보스방까지 가셔야 합니다. 보스는 공략한 후 입니다.

**Comment by wooddoll** [comment]
오우거 방으로 가는 길에 있는 '하이에나...'방에 있는 발판이 안움직이는데, 이것도 버그 인가요?
일어판으로 로드해도 안움직이긴 하네요.
저는 아직 여기까지 진행해본 적이 없어서 어떻게 가는지도 잘 모르겠습니다 :(
![Vagrant Story (Japan, Asia) 2024-11-09-03-42-45](https://github.com/user-attachments/assets/67b94fd2-6494-4aff-91d0-0b243b1d8daf)

0.92에서 텍스트 오류는 수정했습니다.
진행불가 버그는 좀 더 확인해봐야겟습니다.

**Comment by cclownc** [comment]
스크린샷에서 상자를 오른쪽 끝에 두개 쌓고 발판쪽으로 점프하면 아슬아슬하게 닿습니다.   

0.92 패치적용 후에도
진행불가 버그는 나타납니다. 여전히 메뉴버튼이 눌러지지 않고 일정시간 후 게임이 멈춥니다.

**Comment by wooddoll** [comment]
0.93에서 정상적으로 메뉴 불러와지는 것 확인
