### ISSUE TITLE
베이그란트 스토리 v0.93 한글패치 버그

### ISSUE THREAD

**Issue by cclownc** [wooddoll/vagrant_story_korean#4]
![2024111002410600-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/6fcf047b-d782-4e0b-9736-cbb4c05c0ec7)
![2024111002365100-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/47d5ce2c-07e7-4da3-a6fd-434f4663d064)
![2024111002365700-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/3f17bcd9-1979-47c3-b231-3a17f962b8ab)
![2024111002370700-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/95416d57-f581-4fa1-a292-3fb671788589)
![2024111002371100-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/371c0951-ec81-48b0-8a33-7ac9a779dde1)
![2024111002372000-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/b9c022e3-b02d-4ccb-9625-7b9fb972a717)
![2024111002372300-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/f348d9b8-3703-422f-99d5-bfbb8fcbb73f)
![2024111002373100-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/1a368cf2-a6cb-42d8-90e5-b2eb21a68a0d)
![2024111002373400-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/5c34e595-7d33-4364-b769-734f13f3a2e5)
레아몬드 요새 각인이 지도에서는 정상적으로 보이는데 문에서는 이상하게 나옵니다.

![2024111012332600-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/1d09fefc-75d3-4b89-a28a-1adfac32cf4e)
![2024111012333100-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/892caae5-cb80-4dc2-bcc6-4d704c94ac44)
![2024111012333300-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/d25509f1-bd77-4eb5-8447-7d440c3445cc)
이름 바꾸는 창에서 전 버전은 한글로 표기 되었는데 일어로 나옵니다.

![2024111012300200-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/93f335a7-6ba9-44ea-9264-8ac51e73f1ca)
이름 바꾸는 창에서 자모순서를 21페이지 까지 가면 게임이 멈춥니다.

![2024111013254800-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/5a7b38c5-17f4-4025-8dda-d05d44d3c651)
레아몬드 요새에 한정된건지 모르겠지만 죽으면 게임오버창이 아니라 대성당 2층으로 가서 계속 문이 해제되었다는 메세지가 뜹니다.

[memcards.zip](https://github.com/user-attachments/files/17690160/memcards.zip)
혹시 몰라 세이브파일을 첨부합니다. 1슬롯 첫번째 세이브 입니다.

**Comment by wooddoll** [comment]
확인 감사합니다.
0.94에서 수정했습니다.
