### ISSUE TITLE
vagrant_story_korean v0.94 버그

### ISSUE THREAD

**Issue by cclownc** [wooddoll/vagrant_story_korean#5]
굉장히 재밌게 즐기고 있습니다. 패치 감사합니다.

![2024111100051900-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/345bc2bb-3a19-4b28-a403-446bb71911da)
![2024111100265600-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/cd09d3da-a3d5-46c3-b42a-a27293b10655)
![2024111100265800-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/fddbf155-3d61-46f5-ae8a-d9c41b6c39c1)
 텔레포트를 얻고 나서 세이브존에서 텔레포트를 하려고 보면 한글이 되어 있지 않습니다.

**Comment by wooddoll** [comment]
확인 감사합니다.
텔레포트가 있는지도 몰랐네요 ㅎㅎ

가능하면, 텔레포트가 있는 세이브 파일을 올려주실 수 있을까요?

**Comment by cclownc** [comment]
[Vagrant Story (kv0.94).zip](https://github.com/user-attachments/files/17693602/Vagrant.Story.kv0.94.zip)
1슬롯 첫번째 세이브입니다. 세이브존에서만 텔레포트 가능합니다.

**Comment by wooddoll** [comment]
0.95에서 수정되었습니다.

**Comment by wooddoll** [comment]
0.95에서 수정되었습니다.
