### ISSUE TITLE
플스 실기에서 v0.94이후 로딩중 멈춤

### ISSUE THREAD

**Issue by Appletree4870** [wooddoll/vagrant_story_korean#6]
![IMG_20241112_080426654](https://github.com/user-attachments/assets/962c4a5d-e400-497f-9aac-d01783ecd9a3)

안녕하세요.
한글화 덕분에 재미있게 플레이하고 있습니다.
예전 감성때문에 실기를 이용하여 즐기고 있었는데 v0.94버젼 패치 이후 로딩 화면에서 게임이 멈추는 증상이 나오네요.
오프닝영상 이후 시작메뉴까지는 잘나오나 뉴게임, 세이브파일 불러오기 모두 로딩화면에서 프리징되어 버립니다.
v0.93버전까지는 잘 되다가 v0.94버전부터 안되네요.
에뮬에서는 문제없는데 실기에서만 멈춤증상이 나옵니다.
혹시 해결이 될까해서 염치없이 문의드려 봅니다.

**Comment by wooddoll** [comment]
뉴게임에서도 멈춘다면 생각 좀 해봐야겠네요.
저는 실기에서는 테스트 해본적이 없어서 원인 파악하려면 시간이 좀 걸릴 것 같습니다.

**Comment by wooddoll** [comment]
0.96에서 확인해 보시기 바랍니다.
그래도 안되면 다시 이슈 오픈해주세요.

**Comment by wooddoll** [comment]
0.96에서 확인해 보시기 바랍니다.
그래도 안되면 다시 이슈 오픈해주세요.

**Comment by Appletree4870** [comment]
감사합니다! 해결되었어요.
0.96 , 0.97버젼 모두 실기에서 로딩화면 멈춤증상이 사라졌습니다.
구동 잘됩니다.
정말 대단하시네요.
