### ISSUE TITLE
vagrant_story_korean v0.95 버그

### ISSUE THREAD

**Issue by cclownc** [wooddoll/vagrant_story_korean#7]
한글패치 덕분에 재밌게 즐기고 클리어 했습니다.

![2024111122545000-4B8EEF0C772969B2827FD015DDF4A6D8](https://github.com/user-attachments/assets/73df12de-dac7-4f8b-b9d9-4414dca8474a)
적 상태장에 확인되지 않은 부분이 '큐브'라고 나타납니다.

그리고 로딩에서 멈춘다고 전에 글이 있었는데. 
에뮬상에서는 뉴게임 플러스로 해도 멈춤이 없었습니다.
사용한 에뮬은  덕스테이션과 레트로아크psx 코어 입니다.

추가로 엔딩 부분에서 bgm이 갈라져서 나오는데. 원본을 확인해 보고 나중에 첨언하겠습니다.

**Comment by cclownc** [comment]
[Vagrant Story (kv0.95).zip](https://github.com/user-attachments/files/17731216/Vagrant.Story.kv0.95.zip)
혹시 몰라 클리어 세이브도 올리겠습니다.
1슬롯 마지막 세이브 입니다.

**Comment by wooddoll** [comment]
벌써 엔딩까지 봤다니.. 부럽네요. 
전 한글화 한다고 좀 놀았더니 쌓인 일이 많아서 게임을 거의 못하고 있습니다 ㅠ
엔딩까지 bgm과 큐브 말고는 다른 문제점이나 한글화 안된 부분은 은 없었나요?

**Comment by cclownc** [comment]
레이몬데 요새 부터는 딱히 눈에 띄는 부분은 보이지 않았습니다. 

사실 도중 퍼즐이 너무 어려워서 한글패치 때문에 오류가 나서 퍼즐이 바뀐것 아닐까 
의심한적은 있지만 곰곰히 생각하니 다 풀려서 괜히 패치탓을 한 자신을 반성했습니다.

게임 내 달성도는 70% 정도라 게임을 클리어 했다고 해도 보지 못한 부분이 많아 
다회차를 해야 나머지 부분을 볼수 있을것 같습니다.

패치 덕분에 게임을 정말 재밌게 했습니다. 다회차는 천천히 할 생각이지만 
혹여나 이상한 부분이 있다면 바쁘신데 죄송하지만 다시금 여기에 글을 올릴것 같습니다. 

감사합니다.

**Comment by wooddoll** [comment]
0.97에서 수정했습니다. 확인 감사합니다.
